# Generated by Django 2.1.7 on 2019-03-28 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0004_auto_20190328_1936'),
        ('auth', '0009_alter_user_last_name_max_length'),
        ('users', '0002_auto_20190328_1935'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='User',
        ),
    ]
