# Generated by Django 2.1.7 on 2019-04-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190328_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(1, '普通用户'), (2, '管理员'), (3, '超级管理员')], default=1),
        ),
        migrations.DeleteModel(
            name='Token',
        ),
    ]
